version: '2.1'
jobs:
  deploy-prod:
    docker:
    - image: cytopia/terragrunt:0.12-0.19
    environment:
      TF_INPUT: false
    working_directory: /data/prod
    steps:
    - checkout:
        path: /data
    - run:
        command: terragrunt apply-all
workflows:
  version: 2
  deploy:
    jobs:
    - deploy-prod